version: '3'

volumes:
  pg_foodgram:
  static:
  media:

services:
  db_foodgram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_foodgram:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/recipes/images/
    depends_on:
      - db_foodgram

  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile
    volumes:
       - static:/app/result_build/build

  infra:
    build: ./infra/
    volumes:
      - static:/usr/share/nginx/html/
      - media:/media/
    ports:
      - "80:80"