version: '3.3'

volumes:
  pg_foodgram:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_foodgram:/var/lib/postgresql/data

  backend:
    image: kosachmax/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db_foodgram

  frontend:
    env_file: .env
    image: kosachmax/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: kosachmax/foodgram_gateway
    volumes:
      - static:/usr/share/nginx/html/
      - media:/media
    ports:
      - "8000:80"
    depends_on:
      - backend